#!/bin/bash
sudo apt-get update && wget https://minergate.com/download/deb-cli -O minergate-cli.deb && sudo dpkg -i minergate-cli.deb
apt-get install screen
screen minergate-cli -user offatetranphu@gmail.com -xmr
